version: '3.4'

services:
  pessoa:
    image: ${DOCKER_REGISTRY-}pessoa
    build:
      context:               .
      dockerfile: Pessoa/Dockerfile
    depends_on:
      - postgresql_database

  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=pessoadb
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: